(load "../mk/test-check.scm")
(load "error-interp-specific-all.scm")


(test "0a"
  (run* (q) (eval-expo '(lambda (x) x) '() q))
  '((closure x x ())))

(test "0b"
  (run 5 (q) (eval-expo q '() '(closure x x ())))
  '((lambda (x) x)
    (((lambda (_.0) _.0) (lambda (x) x))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0))
    ((car (cons (lambda (x) x) '_.0))
     (absento (ERROR _.0) (closure _.0)))
    ((cdr (cons '_.0 (lambda (x) x)))
     (absento (ERROR _.0) (closure _.0)))
    ((car (cons (lambda (x) x) (lambda (_.0) _.1)))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (closure _.1)))))

(test "8"
  (run 1 (q)
    (eval-expo q '() q))
  '((((lambda (_.0)
        (cons _.0 (cons (cons 'quote (cons _.0 '())) '())))
      '(lambda (_.0)
         (cons _.0 (cons (cons 'quote (cons _.0 '())) '()))))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0))))

(test "9"
  (run 10 (q)
    (eval-expo q '() '(I love you)))
  '('(I love you)
    (cons 'I '(love you))
    ((car '((I love you) . _.0))
     (absento (ERROR _.0) (closure _.0)))
    ((cdr '(_.0 I love you))
     (absento (ERROR _.0) (closure _.0)))
    (((lambda (_.0) '(I love you)) '_.1)
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (closure _.1)))
    (cons 'I (cons 'love '(you)))
    (((lambda (_.0) _.0) '(I love you))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0))
    (((lambda (_.0) '(I love you)) (lambda (_.1) _.2))
     (=/= ((_.0 ERROR)) ((_.0 closure)) ((_.1 ERROR)) ((_.1 closure)))
     (sym _.0 _.1)
     (absento (ERROR _.2) (closure _.2)))
    ((cons (car '(I . _.0)) '(love you))
     (absento (ERROR _.0) (closure _.0)))
    ((cons (cdr '(_.0 . I)) '(love you))
     (absento (ERROR _.0) (closure _.0)))))


(test "0c"
  (run* (q) (eval-expo '(car (lambda (x) x)) '() q))
  '((ERROR ATTEMPT-TO-TAKE-CAR-OF-NON-PAIR (closure x x ()))))

(test "0d"
  (run* (q) (eval-expo '(cdr (lambda (x) x)) '() q))
  '((ERROR ATTEMPT-TO-TAKE-CDR-OF-NON-PAIR (closure x x ()))))

(test "0e"
  (run* (q) (eval-expo '(car (cdr (lambda (x) x))) '() q))
  '((ERROR ATTEMPT-TO-TAKE-CDR-OF-NON-PAIR (closure x x ()))))

(test "3"
  (run* (q)
    (eval-expo `((lambda (y) x) (lambda (z) z)) '() q))
  '((ERROR UNBOUND-VARIABLE x)))

(test "6"
  (run 10 (q msg)
    (eval-expo q '() `(ERROR . ,msg)))
  '(((_.0 (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0))
    (((cons _.0 _.1) (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0)
     (absento (ERROR _.1) (closure _.1)))
    (((cons _.0 _.1) (UNBOUND-VARIABLE _.1))
     (=/= ((_.1 ERROR)) ((_.1 closure))) (sym _.1)
     (absento (ERROR _.0) (closure _.0)))
    (((_.0 _.1) (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 car)) ((_.0 cdr))
          ((_.0 closure)) ((_.0 quote)))
     (sym _.0) (absento (ERROR _.1) (closure _.1)))
    (((_.0 _.1) (UNBOUND-VARIABLE _.1))
     (=/= ((_.0 car)) ((_.0 cdr)) ((_.0 quote)) ((_.1 ERROR))
          ((_.1 closure)))
     (sym _.1) (absento (ERROR _.0) (closure _.0)))
    (((car _.0) (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0))
    (((cdr _.0) (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0))
    (((cons (cons _.0 _.1) _.2) (UNBOUND-VARIABLE _.0))
     (=/= ((_.0 ERROR)) ((_.0 closure))) (sym _.0)
     (absento (ERROR _.1) (ERROR _.2) (closure _.1)
              (closure _.2)))
    (((cons _.0 (cons _.1 _.2)) (UNBOUND-VARIABLE _.1))
     (=/= ((_.1 ERROR)) ((_.1 closure))) (sym _.1)
     (absento (ERROR _.0) (ERROR _.2) (closure _.0)
              (closure _.2)))
    (((cons (cons _.0 _.1) _.2) (UNBOUND-VARIABLE _.1))
     (=/= ((_.1 ERROR)) ((_.1 closure))) (sym _.1)
     (absento (ERROR _.0) (ERROR _.2) (closure _.0)
              (closure _.2)))))

(test "7"
  (run 5 (q val)
    (eval-expo q '() `(ERROR ATTEMPT-TO-TAKE-CAR-OF-NON-PAIR ,val)))
  '((((car (lambda (_.0) _.1))
      (closure _.0 _.1 ()))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (closure _.1)))
    (((cons (car (lambda (_.0) _.1)) _.2)
      (closure _.0 _.1 ()))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (ERROR _.2) (closure _.1) (closure _.2)))
    (((cons _.0 (car (lambda (_.1) _.2)))
      (closure _.1 _.2 ()))
     (=/= ((_.1 ERROR)) ((_.1 closure))) (sym _.1)
     (absento (ERROR _.0) (ERROR _.2) (closure _.0) (closure _.2)))
    ((((car (lambda (_.0) _.1)) _.2)
      (closure _.0 _.1 ()))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (ERROR _.2) (closure _.1) (closure _.2)))
    (((cdr (car (lambda (_.0) _.1)))
      (closure _.0 _.1 ()))
     (=/= ((_.0 ERROR)) ((_.0 closure)))
     (sym _.0)
     (absento (ERROR _.1) (closure _.1)))))

(test "10"
  (run 10 (q)
    (eval-expo q '() `(ERROR UNBOUND-VARIABLE foo)))
  '(foo
    ((cons foo _.0)
     (absento (ERROR _.0) (closure _.0)))
    ((cons _.0 foo)
     (absento (ERROR _.0) (closure _.0)))
    ((foo _.0)
     (absento (ERROR _.0) (closure _.0)))
    ((_.0 foo) (=/= ((_.0 car)) ((_.0 cdr)) ((_.0 quote)))
     (absento (ERROR _.0) (closure _.0)))
    (car foo)
    (cdr foo)
    ((cons (cons foo _.0) _.1)
     (absento (ERROR _.0) (ERROR _.1)
              (closure _.0) (closure _.1)))
    ((cons _.0 (cons foo _.1))
     (absento (ERROR _.0) (ERROR _.1)
              (closure _.0) (closure _.1)))
    ((cons (cons _.0 foo) _.1)
     (absento (ERROR _.0) (ERROR _.1)
              (closure _.0) (closure _.1)))))

(test "11"
  (run* (q)
    (eval-expo '((w x) (y z)) '() q))
  '((ERROR UNBOUND-VARIABLE w)
    (ERROR UNBOUND-VARIABLE x)
    (ERROR UNBOUND-VARIABLE y)
    (ERROR UNBOUND-VARIABLE z)))
